vich_uploader:
    db_driver: orm

    mappings:
        deliveryNote:
            uri_prefix: /uploads/delivery-notes
            upload_destination: '%kernel.project_dir%/public/uploads/delivery-notes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        label:
            uri_prefix: /uploads/labels
            upload_destination: '%kernel.project_dir%/public/uploads/labels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
