<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250710095428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product DROP CONSTRAINT fk_9fae0aed4584665a
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product DROP CONSTRAINT fk_9fae0aed4bd5e4aa
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product DROP CONSTRAINT fk_9fae0aed59d8a214
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipe_product
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit VARCHAR(50) NOT NULL, recipe_id INT NOT NULL, product_id INT NOT NULL, sub_recipe_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_9fae0aed4584665a ON recipe_product (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_9fae0aed4bd5e4aa ON recipe_product (sub_recipe_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_9fae0aed59d8a214 ON recipe_product (recipe_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product ADD CONSTRAINT fk_9fae0aed4584665a FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product ADD CONSTRAINT fk_9fae0aed4bd5e4aa FOREIGN KEY (sub_recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product ADD CONSTRAINT fk_9fae0aed59d8a214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }
}
