<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250706171609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit VARCHAR(50) NOT NULL, recipe_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9FAE0AED59D8A214 ON recipe_product (recipe_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9FAE0AED4584665A ON recipe_product (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product ADD CONSTRAINT FK_9FAE0AED59D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product ADD CONSTRAINT FK_9FAE0AED4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_products DROP CONSTRAINT fk_c52affc44584665a
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_products DROP CONSTRAINT fk_c52affc459d8a214
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipe_products
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE recipe_products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit VARCHAR(50) NOT NULL, recipe_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_c52affc44584665a ON recipe_products (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_c52affc459d8a214 ON recipe_products (recipe_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_products ADD CONSTRAINT fk_c52affc44584665a FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_products ADD CONSTRAINT fk_c52affc459d8a214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product DROP CONSTRAINT FK_9FAE0AED59D8A214
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recipe_product DROP CONSTRAINT FK_9FAE0AED4584665A
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE recipe_product
        SQL);
    }
}
