<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250612115603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE product_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, product_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9AF271FB4584665A ON product_event (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_9AF271FB71F7E88B ON product_event (event_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sale_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, address VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_event ADD CONSTRAINT FK_9AF271FB4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_event ADD CONSTRAINT FK_9AF271FB71F7E88B FOREIGN KEY (event_id) REFERENCES sale_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE category ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE product_event DROP CONSTRAINT FK_9AF271FB4584665A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_event DROP CONSTRAINT FK_9AF271FB71F7E88B
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE product_event
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sale_event
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product DROP created_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE category DROP created_at
        SQL);
    }
}
