<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250709104813 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE step_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, step_id INT NOT NULL, recipe_product_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_63B7824273B21E9C ON step_product (step_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_63B78242CFAE039 ON step_product (recipe_product_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product ADD CONSTRAINT FK_63B7824273B21E9C FOREIGN KEY (step_id) REFERENCES step (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product ADD CONSTRAINT FK_63B78242CFAE039 FOREIGN KEY (recipe_product_id) REFERENCES recipe_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step ADD duration_minutes INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step ADD number INT DEFAULT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product DROP CONSTRAINT FK_63B7824273B21E9C
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product DROP CONSTRAINT FK_63B78242CFAE039
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE step_product
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step DROP duration_minutes
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step DROP number
        SQL);
    }
}
