<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250710195940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product ADD unit_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product DROP unit
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product ADD CONSTRAINT FK_63B78242F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_63B78242F8BD700D ON step_product (unit_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE unit
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product DROP CONSTRAINT FK_63B78242F8BD700D
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_63B78242F8BD700D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product ADD unit VARCHAR(255) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE step_product DROP unit_id
        SQL);
    }
}
