<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250617172716 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE product_allergen (product_id INT NOT NULL, allergen_id INT NOT NULL, PRIMARY KEY(product_id, allergen_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EE0F62594584665A ON product_allergen (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EE0F62596E775A4A ON product_allergen (allergen_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_allergen ADD CONSTRAINT FK_EE0F62594584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_allergen ADD CONSTRAINT FK_EE0F62596E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE product_allergen DROP CONSTRAINT FK_EE0F62594584665A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_allergen DROP CONSTRAINT FK_EE0F62596E775A4A
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE allergen
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE product_allergen
        SQL);
    }
}
