<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250618123545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE delivery_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE product_delivery_note (product_id INT NOT NULL, delivery_note_id INT NOT NULL, PRIMARY KEY(product_id, delivery_note_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C4CC2E7C4584665A ON product_delivery_note (product_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C4CC2E7C2CF3B78B ON product_delivery_note (delivery_note_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_delivery_note ADD CONSTRAINT FK_C4CC2E7C4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_delivery_note ADD CONSTRAINT FK_C4CC2E7C2CF3B78B FOREIGN KEY (delivery_note_id) REFERENCES delivery_note (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label ADD registered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label DROP name
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE product_delivery_note DROP CONSTRAINT FK_C4CC2E7C4584665A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE product_delivery_note DROP CONSTRAINT FK_C4CC2E7C2CF3B78B
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE delivery_note
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE product_delivery_note
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label ADD name VARCHAR(50) DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label DROP created_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE label DROP registered_at
        SQL);
    }
}
